name: test_22_10_2024
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  expandable_page_view: ^1.0.17
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.2
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.1.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/image/
